version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - durationcheck
    # - errcheck
    - copyloopvar
    # - forcetypeassert
    # - godot
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    # - unparam
    - unused
    - govet
    - testifylint

formatters:
  enable:
    - gofmt
    - goimports