services:
    rabbitmq:
        build:
          context: .
          args:
            RABBITMQ_VERSION: ${RABBITMQ_VERSION:-3.13}
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
        ports:
            - 15672:15672
        volumes:
            - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
