name: Build

on:
  push:
    branches-ignore: 
      - main
  pull_request:
  workflow_dispatch: 

jobs:

  ci:
    name: Continous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Install dependencies
        run: |
          go mod download
          go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
      
      - name: Build
        run: go build -v .

      - name: Run Uniting-Tests
        run: go test -json ./... > go-test.json
      
      - name: Publish Uniting-Tests
        run: |
            cat go-test.json | go-ctrf-json-reporter -output ctrf-report.json
            npx github-actions-ctrf summary ctrf-report.json
            npx github-actions-ctrf failed ctrf-report.json
        if: always()

  cd-assets:
    name: Continous Delivry - Assets
    needs: ci
    if: github.ref_name == 'develop' || github.event_name == 'pull_request' || github.event == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: go-linky
          path: |
            dist/*.tar.gz
            dist/*.zip